print("Hello World")
print('hello')
print('hi')
print('how are you')
print('good')
print('bad')
print('fine')
print('all')
<<<<<<< HEAD
print('priya')
print('gud mrng')
print('why this')
=======
print('priya')
>>>>>>> parent of 1dc96e6 (Update a.py)
