print("Hello World")
print('hello')
print('hi')
print('how are you')
print('good')
print('bad')
print('fine')
print('rajani')
print('good bad')
print('afternoon')
print('ram')
print('pranav')
print('raghu')
print('fine')
print('Sree')